table dCalendario
	lineageTag: a1e1f2eb-b868-410b-8da6-617e0c20977d

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e83f4ed-f346-4593-ab18-43d33cf545c1
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 25adbc21-8cad-40cf-bc7f-f71783747344
			defaultHierarchy: LocalDateTable_ffb7dfd0-ba82-4f5f-9218-fee2725afccd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 67f7df91-fb50-4e88-8443-5ad14e04e66c
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 24e1d651-e312-4102-ba10-d408f3578647
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: ebd335d6-9519-44c4-99c1-5cab07f2e7ce
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: Mês

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 4d4f3e2a-d084-47e8-a7ad-fdbf4ce7ca5c
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    Fonte = Consulta1(#date(2017, 1, 1), 1095, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data"}}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Dia Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type)
				in
				    #"Dia Inserido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

